// Shell completion. `sandbox completion <shell>` prints a script the user sources (or installs
// via `sandbox path`). Kept as pure string-builders so the exact output is unit-testable — the CLI
// layer only chooses a shell and writes the result to stdout.

export const COMPLETION_SHELLS = ['zsh', 'bash', 'fish'] as const;
export type CompletionShell = (typeof COMPLETION_SHELLS)[number];

export function isCompletionShell(value: string): value is CompletionShell {
  return (COMPLETION_SHELLS as readonly string[]).includes(value);
}

/**
 * Sandbox-native subcommands plus the expert models and the package-manager front-ends you'd put
 * after `sandbox`. Must track the command dispatch in `cli.ts main()` — `completion.test.ts` only
 * checks each entry appears in the script, so add new commands here when they land.
 */
export const SANDBOX_COMMANDS = [
  'init', 'setup', 'allow', 'off', 'on', 'doctor', 'verify', 'scan', 'secrets', 'feeds', 'delta', 'check', 'preflight', 'approve-builds',
  'badge', 'completion', 'install', 'add', 'remove', 'run', 'x', 'update', 'upgrade', 'audit', 'dev', 'script', 'help', 'version',
  'npm', 'pnpm', 'yarn', 'bun', 'npx', 'bunx', 'node', 'tsx', 'turbo', 'nx',
] as const;

/** Global flags parsed before the command (mirrors `parse()` in cli.ts). */
export const GLOBAL_FLAGS = [
  '--config', '--env', '--env-from', '--frozen',
  '--fail-on-source-writes', '--risk', '--fail-on-risk',
  '--dry-run', '--min-release-age', '--allow-recent', '--deep', '--fail-on-advisory',
  '--allow-deprecated', '--allow-all-builds', '--allow-build-hosts', '--no-update-check', '--json',
] as const;

export const PRESET_VALUES = ['strict', 'balanced', 'vibe', 'agent', 'trusted'] as const;
export const RISK_VALUES = ['off', 'basic', 'thorough'] as const;

const COMMANDS = SANDBOX_COMMANDS.join(' ');
const FLAGS = GLOBAL_FLAGS.join(' ');

export interface CompletionOptions {
  /**
   * Render for sourcing from an rc file (`.zshrc`) rather than installing as a standalone fpath
   * file. Only affects zsh: drops the `#compdef` header (valid only as an fpath file's first line)
   * and guards the `compdef` call so a shell whose completion system isn't loaded yet won't error.
   * bash and fish are already rc-safe and render identically either way.
   */
  inline?: boolean;
}

/** Render the completion script for one shell. Pure. */
export function completionScript(shell: CompletionShell, opts: CompletionOptions = {}): string {
  switch (shell) {
    case 'zsh':
      return zsh(opts.inline ?? false);
    case 'bash':
      return bash();
    case 'fish':
      return fish();
  }
}

function zsh(inline: boolean): string {
  const header = inline
    ? '# sandbox shell completion (zsh)'
    : '#compdef sandbox sandbox-node\n# sandbox shell completion (zsh), generated by `sandbox completion zsh`';
  const register = inline
    ? '(( $+functions[compdef] )) && compdef _sandbox sandbox sandbox-node'
    : 'compdef _sandbox sandbox sandbox-node';
  return `${header}
_sandbox() {
  local -a _sandbox_commands _sandbox_flags
  _sandbox_commands=(${SANDBOX_COMMANDS.map((c) => `'${c}'`).join(' ')})
  _sandbox_flags=(${GLOBAL_FLAGS.map((f) => `'${f}'`).join(' ')})
  _arguments -C '1: :->command' '*:: :->args'
  case $state in
    command)
      _describe 'command' _sandbox_commands ;;
    args)
      case $words[$CURRENT-1] in
        --preset) compadd -- ${PRESET_VALUES.join(' ')} ;;
        --risk) compadd -- ${RISK_VALUES.join(' ')} ;;
        *)
          if [[ $words[$CURRENT] == -* ]]; then
            compadd -- $_sandbox_flags
          else
            case $words[1] in
              init|setup) compadd -- ${PRESET_VALUES.join(' ')} ;;
            esac
          fi ;;
      esac ;;
  esac
}
${register}
`;
}

function bash(): string {
  return `# sandbox shell completion (bash), generated by \`sandbox completion bash\`
_sandbox() {
  local cur prev cmds flags
  COMPREPLY=()
  cur="\${COMP_WORDS[COMP_CWORD]}"
  prev="\${COMP_WORDS[COMP_CWORD-1]}"
  cmds="${COMMANDS}"
  flags="${FLAGS}"
  case "$prev" in
    --preset) COMPREPLY=( $(compgen -W "${PRESET_VALUES.join(' ')}" -- "$cur") ); return ;;
    --risk) COMPREPLY=( $(compgen -W "${RISK_VALUES.join(' ')}" -- "$cur") ); return ;;
  esac
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "$flags" -- "$cur") )
  else
    COMPREPLY=( $(compgen -W "$cmds" -- "$cur") )
  fi
}
complete -F _sandbox sandbox sandbox-node
`;
}

function fish(): string {
  const lines = ['# sandbox shell completion (fish), generated by `sandbox completion fish`'];
  for (const bin of ['sandbox', 'sandbox-node']) {
    lines.push(
      `# ${bin}: commands (only when no subcommand has been typed yet)`,
      `complete -c ${bin} -f -n '__fish_use_subcommand' -a '${COMMANDS}'`,
      `# ${bin}: global flags`,
      ...GLOBAL_FLAGS.map((flag) => `complete -c ${bin} -l ${flag.replace(/^--/, '')}`),
      `# ${bin}: enum-valued flags`,
      `complete -c ${bin} -l preset -x -a '${PRESET_VALUES.join(' ')}'`,
      `complete -c ${bin} -l risk -x -a '${RISK_VALUES.join(' ')}'`,
    );
  }
  return `${lines.join('\n')}\n`;
}
